title: Remove the Archbishop Ryan High School "Raider" Mascot
description: Depicting Indigenous peoples as "Raiders" in the Archbishop Ryan High School mascot is racist. We ask that the ARHS administration change its mascot immediately.
theme: jekyll-theme-minimal